### ISSUE TITLE
Storage - event detail overflow

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#236] opened 2015-06-26 07:39 UTC
![capture_001_26062015_093644](https://cloud.githubusercontent.com/assets/4319320/8372823/179a7d82-1be7-11e5-887b-9d73d3ffeb7f.png)

**Comment by ujovlado** [comment] 2018-08-21 22:57
Duplicate of https://github.com/keboola/indigo-ui/issues/246

**Closed by ujovlado** 2018-08-21 22:57 UTC
